### ISSUE TITLE
There are that any case of build fails

### ISSUE THREAD

**Issue by okunokentaro** [mizchi-sandbox/arda-starter-project#1]
I have some issues about building.

**1. Possibly is `src/contexts/sub/subscriber.ts` missing?**

```
[11:16:30] Error in plugin 'gulp-shell'
Message:
    Command failed: /bin/sh -c ./node_modules/.bin/tsc -d -m commonjs  --preserveConstEnums -t es5 --sourceMap --outDir lib src/entry.ts

Details:
    killed: false
    code: 3
    signal: null
    cmd: /bin/sh -c ./node_modules/.bin/tsc -d -m commonjs  --preserveConstEnums -t es5 --sourceMap --outDir lib src/entry.ts
    stdout: src/contexts/sub/index.ts(1,29): error TS2307: Cannot find external module './subscriber'.

    stderr:
```

**2. node-sass requires Node 0.12.0 in fact.**

```
> node-sass@2.0.1 install /Users/---/Desktop/arda-starter-project-master/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/darwin-x64-node-0.11/binding.node

> node-sass@2.0.1 postinstall /Users/---/Desktop/arda-starter-project-master/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/---/Desktop/arda-starter-project-master/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Build failed
```

`https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/darwin-x64-node-0.11/binding.node` is not been maintained. node-sass requires Node 0.12.0 in fact.
- https://github.com/sass/node-sass-binaries

**3. A proposal of building.**

```
npm install
node_modules/.bin/dtsm install
node_modules/.bin/gulp build       <- may be required.
node_modules/.bin/gulp build:web

open public/index.html
```

These are non-use `npm install -g dtsm gulp`.
Thanks.

**Comment by mizchi** [comment]
:+1: 

I will fix so

**Comment by mizchi** [comment]
Fixed
